package com.serisoft.model;

//Generated 6 mai 2013 08:27:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * TPersonne generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "T_PERSONNE")
public class Personne implements java.io.Serializable {

	private Integer id;
	private Integer version;
	private String nom;
	private String prenom;
	private Short age;
	private Short nbenfants;
	private short marie;

	public Personne() {
	}

	public Personne(int id, String nom, short marie) {
		this.id = id;
		this.nom = nom;
		this.marie = marie;
	}

	public Personne( String nom, String prenom, short age) {
		//this.id = id;
		this.nom = nom;
		this.prenom = prenom;
		this.age = age;
	}
	
	public Personne(int id, String nom, String prenom, Short age,
			Short nbenfants, Date dateNais, short marie) {
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
		this.age = age;
		this.nbenfants = nbenfants;
		this.marie = marie;

	}
	
	public void edit(Personne p){
		this.nom = p.getNom();
		this.prenom = p.getPrenom();
		this.age = p.getAge();
		this.nbenfants = p.getNbenfants();
		this.marie = p.getMarie();
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "NOM", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "AGE")
	public Short getAge() {
		return this.age;
	}

	public void setAge(Short age) {
		this.age = age;
	}

	@Column(name = "NBENFANTS")
	public Short getNbenfants() {
		return this.nbenfants;
	}

	public void setNbenfants(Short nbenfants) {
		this.nbenfants = nbenfants;
	}

	@Column(name = "MARIE", nullable = false)
	public short getMarie() {
		return this.marie;
	}

	public void setMarie(short marie) {
		this.marie = marie;
	}

	@Override
	public String toString() {
		String s = "TPersonne [id=" + id + ", nom=" + nom + ", prenom="
				+ prenom + "]";

		return s;

	}

}
